// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPaths(arg1) {
  return window['go']['main']['App']['AddPaths'](arg1);
}

export function Cancel(arg1) {
  return window['go']['main']['App']['Cancel'](arg1);
}

export function ClearFinished() {
  return window['go']['main']['App']['ClearFinished']();
}

export function Enqueue(arg1, arg2, arg3) {
  return window['go']['main']['App']['Enqueue'](arg1, arg2, arg3);
}

export function Move(arg1, arg2) {
  return window['go']['main']['App']['Move'](arg1, arg2);
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function PickISOs() {
  return window['go']['main']['App']['PickISOs']();
}

export function PickOutputDir(arg1) {
  return window['go']['main']['App']['PickOutputDir'](arg1);
}

export function Ready() {
  return window['go']['main']['App']['Ready']();
}

export function RecheckMkvmerge() {
  return window['go']['main']['App']['RecheckMkvmerge']();
}

export function ReloadConfig() {
  return window['go']['main']['App']['ReloadConfig']();
}

export function Remove(arg1) {
  return window['go']['main']['App']['Remove'](arg1);
}

export function RemoveDisc(arg1) {
  return window['go']['main']['App']['RemoveDisc'](arg1);
}

export function Rename(arg1, arg2) {
  return window['go']['main']['App']['Rename'](arg1, arg2);
}

export function Retry(arg1) {
  return window['go']['main']['App']['Retry'](arg1);
}

export function Reveal(arg1) {
  return window['go']['main']['App']['Reveal'](arg1);
}

export function SetPaused(arg1) {
  return window['go']['main']['App']['SetPaused'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
