// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPaths(arg1:Array<string>):Promise<void>;

export function Cancel(arg1:string):Promise<void>;

export function ClearFinished():Promise<void>;

export function Enqueue(arg1:string,arg2:Array<string>,arg3:Array<string>):Promise<Array<string>>;

export function MkvmergeInfo():Promise<string>;

export function MkvmergeSourceURL():Promise<string>;

export function Move(arg1:string,arg2:number):Promise<void>;

export function PickFolder():Promise<void>;

export function PickISOs():Promise<void>;

export function PickOutputDir(arg1:string):Promise<void>;

export function Platform():Promise<string>;

export function Ready():Promise<void>;

export function RecheckMkvmerge():Promise<void>;

export function ReloadConfig():Promise<void>;

export function Remove(arg1:string):Promise<void>;

export function RemoveDisc(arg1:string):Promise<void>;

export function Rename(arg1:string,arg2:string):Promise<string>;

export function Retry(arg1:string):Promise<void>;

export function Reveal(arg1:string):Promise<string>;

export function SetPaused(arg1:boolean):Promise<void>;

export function Version():Promise<string>;
